
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MOD = 9;
  public static final int MENOS = 6;
  public static final int IGUALIGUAL = 25;
  public static final int MENOR = 22;
  public static final int PTVIRG = 2;
  public static final int IDENT = 27;
  public static final int MENORIGUAL = 24;
  public static final int KW_IF = 18;
  public static final int IGUAL = 10;
  public static final int PTO = 4;
  public static final int MAIORIGUAL = 23;
  public static final int ABREPAR = 11;
  public static final int ABRE_COLCH = 15;
  public static final int FECHA_COLCH = 16;
  public static final int MAIS = 5;
  public static final int ABRECHAVE = 13;
  public static final int NUMBER = 28;
  public static final int EOF = 0;
  public static final int MULT = 7;
  public static final int KW_WHILE = 20;
  public static final int VIRG = 3;
  public static final int DIV = 8;
  public static final int MAIOR = 21;
  public static final int error = 1;
  public static final int FECHACHAVE = 14;
  public static final int FECHAPAR = 12;
  public static final int KW_PROGRAM = 17;
  public static final int KW_ELSE = 19;
  public static final int DIF = 26;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PTVIRG",
  "VIRG",
  "PTO",
  "MAIS",
  "MENOS",
  "MULT",
  "DIV",
  "MOD",
  "IGUAL",
  "ABREPAR",
  "FECHAPAR",
  "ABRECHAVE",
  "FECHACHAVE",
  "ABRE_COLCH",
  "FECHA_COLCH",
  "KW_PROGRAM",
  "KW_IF",
  "KW_ELSE",
  "KW_WHILE",
  "MAIOR",
  "MENOR",
  "MAIORIGUAL",
  "MENORIGUAL",
  "IGUALIGUAL",
  "DIF",
  "IDENT",
  "NUMBER"
  };
}

